#ifndef __MACOS_KEYMAP_H__
#define __MACOS_KEYMAP_H__

#include "macos_local.h"

struct keymap
{
  uint32_t keyname;
  uint32_t keycode;
};

static struct keymap const darwin_scancode_table[] = {
  { 'a', 0 },
  { 's', 1 },
  { 'd', 2 },
  { 'f', 3 },
  { 'h', 4 },
  { 'g', 5 },
  { 'z', 6 },
  { 'x', 7 },
  { 'c', 8 },
  { 'v', 9 },
  //    { 'nonusbackslash', 10 },
  { 'b', 11 },
  { 'q', 12 },
  { 'w', 13 },
  { 'e', 14 },
  { 'r', 15 },
  { 'y', 16 },
  { 't', 17 },
  { '1', 18 },
  { '2', 19 },
  { '3', 20 },
  { '4', 21 },
  { '6', 22 },
  { '5', 23 },
  { '=', 24 },
  { '9', 25 },
  { '7', 26 },
  { '-', 27 },
  { '8', 28 },
  { '0', 29 },
  { ']', 30 },
  { 'o', 31 },
  { 'u', 32 },
  { '[', 33 },
  { 'i', 34 },
  { 'p', 35 },
  { WI_KEY_ENTER, 36 },
  { 'l', 37 },
  { 'j', 38 },
  { '\'', 39 },
  { 'k', 40 },
  { ';', 41 },
  { '\\', 42 },
  { ',', 43 },
  { '/', 44 },
  { 'n', 45 },
  { 'm', 46 },
  { '.', 47 },
  { WI_KEY_TAB, 48 },
  { WI_KEY_SPACE, 49 },
  { '`', 50 },
  { WI_KEY_BACKSPACE, 51 },
  { WI_KEY_KP_ENTER, 52 },
  { WI_KEY_ESCAPE, 53 },
  //    { 'rgui', 54 }, // rgui
  //    { 'lgui', 55 }, // lgui
  { WI_KEY_SHIFT, 56 }, // lshift
                   //    { 'capslock', 57 }, // capslock
  { WI_KEY_ALT, 58 },   // lalt
  { WI_KEY_CTRL, 59 },  // lctrl
  { WI_KEY_SHIFT, 60 }, // rshift
  { WI_KEY_ALT, 61 },   // ralt
  { WI_KEY_CTRL, 62 },  // rctrl
                   //    { 'rgui', 63 }, // rgui
                   //    { 'f17', 64 },
                   //    { 'kp_period', 65 },
                   //    { 'unknown', 66 },
                   //    { 'kp_multiply', 67 },
                   //    { 'unknown', 68 },
                   //    { 'kp_plus', 69 },
                   //    { 'unknown', 70 },
                   //    { 'numlockclear', 71 },
                   //    { 'volumeup', 72 },
                   //    { 'volumedown', 73 },
                   //    { 'mute', 74 },
  { WI_KEY_KP_SLASH, 75 },
  { WI_KEY_KP_ENTER, 76 },
  //    { 'unknown', 77 },
  //    { 'kp_minus', 78 },
  //    { 'f18', 79 },
  //    { 'f19', 80 },
  //    { 'kp_equals', 81 },
  //    { 'kp_0', 82 },
  //    { 'kp_1', 83 },
  //    { 'kp_2', 84 },
  //    { 'kp_3', 85 },
  //    { 'kp_4', 86 },
  //    { 'kp_5', 87 },
  //    { 'kp_6', 88 },
  //    { 'kp_7', 89 },
  //    { 'unknown', 90 },
  //    { 'kp_8', 91 },
  //    { 'kp_9', 92 },
  //    { 'international3', 93 },
  //    { 'international1', 94 },
  //    { 'kp_comma', 95 },
  { WI_KEY_F5, 96 },
  { WI_KEY_F6, 97 },
  { WI_KEY_F7, 98 },
  { WI_KEY_F3, 99 },
  { WI_KEY_F8, 100 },
  { WI_KEY_F9, 101 },
  //    { 'lang2', 102 },
  { WI_KEY_F11, 103 },
  //    { 'lang1', 104 },
  //    { 'printscreen', 105 },
  //    { 'f16', 106 },
  //    { 'scrolllock', 107 },
  //    { 'unknown', 108 },
  { WI_KEY_F10, 109 },
  //    { 'application', 110 },
  { WI_KEY_F12, 111 },
  //    { 'unknown', 112 },
  //    { 'pause', 113 },
  //    { 'insert', 114 },
  { WI_KEY_HOME, 115 },
  { WI_KEY_PGUP, 116 },
  { WI_KEY_DEL, 117 },
  { WI_KEY_F4, 118 },
  { WI_KEY_END, 119 },
  { WI_KEY_F2, 120 },
  { WI_KEY_PGDN, 121 },
  { WI_KEY_F1, 122 },
  { WI_KEY_LEFTARROW, 123 },
  { WI_KEY_RIGHTARROW, 124 },
  { WI_KEY_DOWNARROW, 125 },
  { WI_KEY_UPARROW, 126 },
  //    { 'power', 127 },
  { 0, 0 }
};

#endif
